### ISSUE TITLE
SkinShare无法使用原武将动态皮肤

### ISSUE THREAD

**Issue by TianyaSKY** [universe-st/qianhuan#3]
<img width="188" alt="image" src="https://github.com/universe-st/qianhuan/assets/93835113/7ca1a33e-ebb7-4700-bea2-ded3597a63ff">
<img width="188" alt="image" src="https://github.com/universe-st/qianhuan/assets/93835113/bfbb4d16-a4b6-4151-9c42-1e9666abe16d">
<img width="646" alt="image" src="https://github.com/universe-st/qianhuan/assets/93835113/7fb68d0c-611c-4610-9ccb-abd30bc0f950">
<img width="706" alt="image" src="https://github.com/universe-st/qianhuan/assets/93835113/d0b4e13e-5e3a-4783-b006-5a6e2cc4a651">

**Comment by universe-st** [comment]
请用手杀换肤小窗口。

**Comment by TianyaSKY** [comment]
<img width="625" alt="image" src="https://github.com/universe-st/qianhuan/assets/93835113/84685d1b-66fb-49ad-9b24-e8d24e9eca1f">
<img width="625" alt="image" src="https://github.com/universe-st/qianhuan/assets/93835113/7bab9229-b93c-444f-85e3-c86252c41abc">
<img width="1150" alt="image" src="https://github.com/universe-st/qianhuan/assets/93835113/3d142ea8-de83-45e2-8cbc-40608452498e">
仍然如此

**Comment by TianyaSKY** [comment]
<img width="219" alt="image" src="https://github.com/universe-st/qianhuan/assets/93835113/5dc1b30e-92ef-4bae-ab25-2ee5352d5a56">

**Comment by universe-st** [comment]
![337AF9BED0F437F695586E09B559B259](https://github.com/universe-st/qianhuan/assets/16679065/8f16541c-4a6d-4fdc-ae4b-f8c4297402e9)

需要在十周年UI的dynamicSkin.js内配置。
